### ISSUE TITLE
希望支持gromore

### ISSUE THREAD

**Issue by J-Yaleen** [gstory0404/GTAds#11]
### 描述
> 异常/需求具体描述

我们想接入穿山甲gromore
然后发现
- GTAds 好像只支持非聚合穿山甲SDK？
- https://github.com/gstory0404/gromore 好像只支持ios

需求
- 请问什么时候可以支持gromore

### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
gromore本身就是一个聚合广告SDK，所以可以独立去使用gromore，而非集成到GTAds中
