### ISSUE TITLE
GTAds快手广告SDK升级

### ISSUE THREAD

**Issue by nnianhouss** [gstory0404/GTAds#13]
希望可以升级一下快手SDK

**Comment by gstory0404** [comment]
暂无开发者账号，无法进入后台下载最新的文档

**Comment by yyds-x** [comment]
给你下好了 大佬辛苦了
iOS SDK 
[KSAdSDK-ad-3.3.55-1627.tar.gz](https://github.com/gstory0404/GTAds/files/13611409/KSAdSDK-ad-3.3.55-1627.tar.gz)
Android SDK
[kssdk-ad-3.3.57-publishRelease-e7bc3aadc2-583.zip](https://github.com/gstory0404/GTAds/files/13611415/kssdk-ad-3.3.57-publishRelease-e7bc3aadc2-583.zip)

**Comment by gstory0404** [comment]
@yyds-x 已更新1.3.1
