### ISSUE TITLE
尝试加载 Pangle 插件，但是插件状态是 UN_INSTALLED。插件安装超时

### ISSUE THREAD

**Issue by shichun-yu** [gstory0404/GTAds#15]
### 
> 尝试加载 Pangle 插件，但是插件状态是 UN_INSTALLED。插件安装超时

### 设备版本
   flutter3，夜神模拟器  build:gradle:7.2.0

### 插件版本
  广告基础库 必须引入
  gtads: ^1.3.0
  需要使用的广告按需引入,以下可选
  字节穿山甲广告
  gtads_csj: ^1.3.5
  腾讯优量汇广告
  gtads_ylh: ^1.3.4
  sigmob广告
  gtads_sigmob: ^1.3.0
  百度百青藤广告
  gtads_bqt: ^1.3.1
  快手广告
  gtads_ks: ^1.3.0

### 日志
A Dart VM Service on SM N976N is available at: http://127.0.0.1:13839/O1-IjccyUzw=/
E/libEGL  ( 7883): called unimplemented OpenGL ES API
The Flutter DevTools debugger and profiler on SM N976N is available at:
http://127.0.0.1:13842?uri=http://127.0.0.1:13839/O1-IjccyUzw=/
D/ProfileInstaller( 7883): Installing profile for com.deepindo.doxiaomimall
W/Zeus/load_pangle( 7883): PluginLoader loadPlugin, UN_INSTALLED, com.byted.pangle
W/TTPluginManager( 7883): Install wait time out
W/System.err( 7883): com.bytedance.sdk.openadsdk.api.plugin.r: (8, install wait timeout)
W/System.err( 7883):    at com.bytedance.sdk.openadsdk.api.plugin.yh.ws(Unknown Source)
W/System.err( 7883):    at com.bytedance.sdk.openadsdk.api.plugin.yh.r(Unknown Source)
W/System.err( 7883):    at com.bytedance.sdk.openadsdk.api.plugin.yh.ws(Unknown Source)
W/System.err( 7883):    at com.bytedance.sdk.openadsdk.api.r$1.run(Unknown Source)
W/System.err( 7883):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err( 7883):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err( 7883):    at java.lang.Thread.run(Thread.java:761)
E/_tt_ad_sdk_( 7883): int sdk failed, code: 4205, message: (8, install wait timeout)
E/初始化( 7883): 失败 4205  (8, install wait timeout)
I/flutter ( 7883): 广告加载结果 [{csj: false}]
I/Zeus/init_pangle( 7883): ZeusScanRunnable listPluginDownloadDir, dir = /data/user/0/com.deepindo.doxiaomimall/app_tt_pangle_bykv_file/pangle_com.byted.pangle/next
D/NetworkSecurityConfig( 7883): No Network Security Config specified, using platform default
I/Zeus/init_pangle( 7883): ZeusScanRunnable listPluginDownloadDir, dir = /storage/emulated/0/Android/data/com.deepindo.doxiaomimall/files/.pangle_d
Application finished.

已做的尝试
 1. 重装依赖 ==> 还是这个报错
 2. 升级了  gtads_csj （之前是1.3.4  目前是 1.3.5）

**Comment by gstory0404** [comment]
@shichun-yu 使用真机测试，官方sdk不支持模拟器

**Comment by shichun-yu** [comment]
非常感谢您的答复~ 已解决
