### ISSUE TITLE
No implementation found for method register on channel baiduad

### ISSUE THREAD

**Issue by sing1** [gstory0404/GTAds#18]
gtads: ^1.3.0
  // 字节穿山甲广告
  gtads_csj: ^1.3.3
 // 百度百青藤广告
  gtads_bqt: ^1.3.1

![image](https://github.com/user-attachments/assets/9096e1a8-82e8-44ae-bfd2-7c9f0dbb83d2)

**Comment by gstory0404** [comment]
flutter clean
flutter pub get
重新运行试试

**Comment by sing1** [comment]
可以了...
