### ISSUE TITLE
ks 快手开屏广告播放完成，没有回调！！！

### ISSUE THREAD

**Issue by langyuxiansheng** [gstory0404/GTAds#21]
### 描述
> 异常/需求具体描述
一共集成了5家的，目前测试了快手的，快手的广告完成后，没回调，就相当于一直卡在开屏页面了。
### 设备版本
> 本地flutter版本、设备型号版本
ios 15.4
### 插件版本
> 插件版本号
目前最新的
### 日志
> 详细的log日志或者截图录屏
```
![image](https://github.com/user-attachments/assets/4404c1dd-6014-42f5-90c2-45cbdb091011)

```

**Comment by gstory0404** [comment]
一更新
