### ISSUE TITLE
有支持Admob的计划吗？

### ISSUE THREAD

**Issue by zeewell** [gstory0404/GTAds#3]
请问，有支持Admob的计划吗？

**Comment by gstory0404** [comment]
暂时插件只支持国内相关广告

**Comment by zeewell** [comment]
如果我自己 GTAds 中接入 [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) 插件是否可行？有什么需要特别注意的事项吗？

**Comment by gstory0404** [comment]
https://github.com/gstory0404/GTAds/blob/master/expand.md @zeewell 自定义文档，具体可以参考 支持插件的定义
