### ISSUE TITLE
[gtads_ylh] 这个插件是否也能够支持 竞价模式 呢？

### ISSUE THREAD

**Issue by zeewell** [gstory0404/GTAds#4]
优量汇的插件默认没有支持竞价模式，是否能够支持 竞价模式 呢？比如给个配置的选项？

如果能正常运行的话，那么会非常灵活。不仅支持多个provider，而且优量汇自己又可以竞价。

没认真研究过，不知道是否可行？

**Comment by gstory0404** [comment]
所有广告插件均做了竞价模式的话，聚合插件可以加入竞价模式。暂时只有优量汇做了竞价模式，其他的广告暂时没有这个功能。所以先不弄了
