### ISSUE TITLE
provider的选择上是否可以支持概率的配置？

### ISSUE THREAD

**Issue by zeewell** [gstory0404/GTAds#5]
目前看有两种，一个是优先级、一个是完全随机，是否方便支持按概率？

**Comment by gstory0404** [comment]
> 目前看有两种，一个是优先级、一个是完全随机，是否方便支持按概率？

- GTAdsModel.PRIORITY优先级模式 当前广告位的优先级数值越大越优先加载（当加载失败后从剩余广告中按数值大小依次重试）
- GTAdsModel.RANDOM随机模式 当前广告位出现的概率必须大于0,如果小于0则不会加载该广告,数值越大出现的概率越高（当加载失败后从剩余广告中重新随机加载）
@zeewell

**Comment by zeewell** [comment]
比如，我想70%的概率显示优量汇的广告，而30的概率显示穿山甲，现在就没办法实现。

如果支持按配置概率来展示，比如，我给优量汇设置为7，而穿山甲设置为3，那么就可以了。

**Comment by gstory0404** [comment]
@zeewell 随机模式原理是 所有广告位的出现概率总和中取一个随机数，然后依次匹配是在哪个区间内，来决定加载哪个厂商广告。并非完全随机加载广告，仍受probability字段控制。
详细可以看代码 https://github.com/gstory0404/GTAds/blob/master/gtads/lib/gtads_util.dart

**Comment by gstory0404** [comment]
优量汇设置为7，穿山甲设置为3，理论上优量汇出现的概率就是无限接近70%

**Comment by zeewell** [comment]
嗯，那可以。这样的话，实际应该理解为就是概率上的哈，不是完全随机。估计得改下文档～～

**Comment by gstory0404** [comment]
文档已更新
