### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by pensacola1989** [gstory0404/GTAds#6]
你好，很棒的插件，但是在安卓上编译遇到如下报错信息，应该是kotlin版本问题，我其他插件可能有版本的要求，我考虑降级Gradle，但是怕影响别的插件，这个flutter-tencent的kotlin依赖，能否提高一些，如1.5x/1.6x?谢谢

``` bash
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_tencentad' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

**Comment by gstory0404** [comment]
考虑到兼容性，kotlin版本不会升级太高，可以考虑降低项目的Gradle版本 @pensacola1989

**Comment by pensacola1989** [comment]
@gstory0404 但是很奇怪。我朋友也用你这个，他kotlin的版本跟我一样，gradle是7.1.3,我是7.3.1，😂， 我先降级Gradle试试吧。
