### ISSUE TITLE
信息流广告

### ISSUE THREAD

**Issue by error-code** [gstory0404/GTAds#8]
### 描述
> 列表创建多个信息流广告，广告内容都是重复

### 设备版本
> Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.19045.2728], locale zh-CN)

### 插件版本
> gtads_csj: ^1.2.2                     #穿山甲广告
  gtads_ylh: ^1.2.1                     #优量汇

### 日志
> 详细的log日志或者截图录屏
```
列表创建多个信息流广告，广告内容都是重复
```

**Comment by gstory0404** [comment]
广告重复可以尝试申请多个key，插件对广告不做任何缓存，每次加载均拉取新的物料，如果重复的话 sdk返回的就是相同的广告 @error-code
